embrapiiCovid19/embrapiiCovid19/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

embrapiiCovid19/users/urls.py
from django.urls import path 

from .views import UserListView, UserDetailView, UserCreate, UserEdit, UserDelete

urlpatterns = [
    path('users/delete/<int:id>', UserDelete, name="user_delete"),
    path('users/edit/<int:id>', UserEdit, name="user_edit"),
    path('users/new/', UserCreate, name='user_new'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('', UserListView.as_view(), name='home')
]

embrapiiCovid19/users/models.py
from django.db import models
from django.urls import reverse


class TestType(models.Model):
    #RT-PCR, Sorologia, Teste Rápido - Antígenos, Teste Rápido - Anticorpos
    name = models.CharField(max_length=50, default='RT-PCR')

    def __str__(self):
        return self.name
        

    

class User(models.Model):
    name = models.CharField(max_length=200)
    born_date = models.DateField()
    test_type = models.ForeignKey(TestType, on_delete=models.CASCADE)


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('user_detail', args=[str(self.id)])

    

embrapiiCovid19/users/forms.py
from datetime import date

from django.forms import ModelForm, DateInput, TimeInput, TextInput, IntegerField
from django.core.exceptions import ValidationError

from .models import User

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={"type": "string"}),
            'born_date': DateInput(attrs={"type": "date"}),
        }

embrapiiCovid19/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView

from .models import User
from .forms import UserForm

class UserListView(ListView):
    model = User 
    template_name = 'home.html'

class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'

def UserCreate(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home")
    else:
        form = UserForm()
    return render(request, "user_new.html", {"form": form})

def UserEdit(request, id):
    
    user = get_object_or_404(User, pk=id)
    if request.method == "POST":
        
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()

            return redirect("home")
    else:
        form = UserForm(instance=user)
    return render(request, "user_edit.html", {"form": form})

def UserDelete(request, id):
    
    user = get_object_or_404(User, pk=id)
    if request.method == "POST":
        user.delete()
        return redirect("home")
    else:
        return render(request, "user_delete.html", {"user": user})

embrapiiCovid19/templates/base.html
{% load static %}
<html>
    <head>
        <title>Controle de testes de COVID-19</title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet" />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
            integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
            crossorigin="anonymous"
        />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'home' %}">Dashboard de Testes</a>
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}"
                            >Listagem de testes <span class="sr-only">(current)</span></a
                        >
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_new' %}">Cadastrar novo teste</a>
                    </li>
                </ul>
            </div>
        </nav>
        
        <div clas="container">
            {% block content %} {% endblock content %}
        </div>

        <script
            src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

embrapiiCovid19/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %} 
{% block content %}
<div class="col-lg-12">
    <div class="row my-4 card-wrapper">
        {% if user_list %} 
        {% for user in user_list %}
        <div class="col-lg-3 col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ user.name }}</h5>
                    <h7 class="card-title">Teste Realizado: {{ user.test_type }}</h7>
                    <p class="card-text">{{ user.born_date }}</p>
                    <a href="{% url 'user_detail' user.id %}" class="btn btn-info">Detalhes</a>
                </div>
            </div>
        </div>
        {% endfor %} 
        {% else %}
        <h1 class="offset-lg-3">No items to show.</h1>
        {% endif %}
    </div>
</div>
{% endblock content %}

embrapiiCovid19/templates/user_delete.html
{% extends "base.html" %}

{% block title %}Deletar User: {{user.name}}{% endblock %}

{% block content %}
<div class="container">
    <h1>Deletar {{user.name}}</h1>
    <form method="post">
        {% csrf_token %}
        <div class="alert alert-danger" role="alert">
            Tem certeza que deseja deletar esse item?
        </div>

        <button type="submit" class="btn btn-danger">Sim</button>
        <a href="{% url 'home' %}" >Não, voltar para home</a>
    </form>
</div>

{% endblock %}

embrapiiCovid19/templates/user_detail.html
{% extends 'base.html' %} 
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">{{ user.name }}</h1>
        <h4>Data de nascimento: {{user.born_date}}</h4>
        <hr class="my-4">
        <h4>Testes realizados</h4>
        <p>{{ user.test_type }}</p>

        <a href="{% url 'user_edit' user.id %}" class="btn btn-info">Editar</a>
        <a href="{% url 'user_delete' user.id %}" class="btn btn-danger   ">Excluir</a>
    </div>
{% endblock content %}

embrapiiCovid19/templates/user_edit.html
{% extends "base.html" %}

{% block title %}Editar Usuário: {{ user.name }}{% endblock %}

{% load crispy_forms_tags %} 

{% block content %}
<div class="container">
    <h1>Editar Usuário</h1>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.born_date|as_crispy_field }}
            </div>
        </div>
        {{ form.test_type|as_crispy_field }}
        <button type="submit" class="btn btn-success">Atualizar</button>
    </form>
</div>
{% endblock %}

embrapiiCovid19/templates/user_new.html
{% extends "base.html" %} 

{% block title %}Novo Teste{% endblock %} 

{% load crispy_forms_tags %} 

{% block content %}

<div class="container">
    <h1>Cadastrar novo usuário</h1>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.born_date|as_crispy_field }}
            </div>
        </div>
        {{ form.test_type|as_crispy_field }}
        <button type="submit" class="btn btn-success">Criar</button>
    </form>
</div>
{% endblock %}